### ISSUE TITLE
How to accses gitlab.ethz.ch?

### ISSUE THREAD

**Issue by logindiamant** [szebedy/autonomous-drone#1]
Please, tel how to accses gitlab.ethz.ch?
git clone https://gitlab.ethz.ch/disco-students/fs18/bszebedy.git catkin_ws
Username for 'https://gitlab.ethz.ch': 
Password for 'https://gitlab.ethz.ch':

**Comment by brunnergino** [comment]
Hi

Thanks for catching that. This was an artifact from our internal git repo. It should of course be the clone command for this Github repo, so

`git clone https://github.com/szebedy/autonomous-drone.git catkin_ws`

Cheers
