### ISSUE TITLE
The question about local position

### ISSUE THREAD

**Issue by Gatsby23** [szebedy/autonomous-drone#12]
When I run the simulation, the drone haven't received the local position message. In offboard_module, there have topic advertise the “ /mavros/local_position/pose ”, but where does it publish ?

**Comment by szebedy** [comment]
The offboard control only subscribes to /mavros/local_position/pose topic, it does not publish (DroneControl::local_position_cb function will be called with the new pose). The px4 simulator is resonsible for publishing the pose.

**Comment by Gatsby23** [comment]
I'm sorry. I'm still confused.... The local position of drone should be estimated by the svo algorithm. Why the px4 simulator publish it ?

**Comment by szebedy** [comment]
The local position estimated by the svo algorithm is published on the /svo/pose_imu topic. The px4 simulator fuses this information with the IMU data and publishes a better estimate on the  /mavros/local_position/pose topic.
