### ISSUE TITLE
Simulation problem

### ISSUE THREAD

**Issue by zxp771** [szebedy/autonomous-drone#4]
Hi @szebedy 
Thanks for your sharing.
I have some question about the simulation.
1. Your introduction(simulation launch everything in the same window with a launch file) said we need launch svo_ros intel_aero. launch like this:
![image](https://user-images.githubusercontent.com/35118859/50848401-32a5b280-1342-11e9-9ca8-7faeb0c5d81f.png)
I'm wondering could I use other algorithm's launch file(maybe I can write a new launch.file for my algorithm like yours) instead of it?
2. For launch each component separately method.
I tried to do the test step by step as your introduction but when I run the "source Tools/setup_gazebo.bash $(pwd) $(pwd)/build/posix_sitl_default" it will show this error:
![image](https://user-images.githubusercontent.com/35118859/50848863-59b0b400-1343-11e9-8dac-269aeac81ea6.png)
could you give me some advice to solve this problem?

Thanks for your sharing again It's really helpful!

**Comment by szebedy** [comment]
Hi @zxp771,
1. My code is expecting the position updates from svo on the topic `/svo/pose_imu`, see https://github.com/szebedy/autonomous-drone/blob/746991207d4eed0af8cb27870ad4d74411fdd314/src/offboard_control/ros_client.cpp#L32
 so if you want use an other visual odometry algorithm you're going to have to change this dependency
2. Looks like the file is not there, maybe you missed initializing the submodules after cloning the repository?
```
cd ~/catkin_ws
git submodule update --init --recursive
```

**Comment by zxp771** [comment]
Hi @szebedy 
Thanks for your reply.
1.thanks for your explanation. I will notice it when I use it.
2. I tried your advice it still didn't work.
Here are the folders in my workspace.
![image](https://user-images.githubusercontent.com/35118859/50849799-08ee8a80-1346-11e9-9c36-0454c346fd8b.png)
BTW all the code in your project has been compiled successfully.

**Comment by szebedy** [comment]
The command `source Tools/setup_gazebo.bash $(pwd) $(pwd)/build/posix_sitl_default` executes the file Tools/setup_gazebo.bash in the `px4` folder. The only reason I can think of not to have that file is that the px4 submodule has not been initialized.

**Comment by zxp771** [comment]
Hi @szebedy 
I noticed that your introduction said:"Wait until downloading finish correctly, then run"
![image](https://user-images.githubusercontent.com/35118859/50861659-63e4a980-1367-11e9-8b93-8081bc1ce43c.png)
but when I run the 
"cd ~/catkin_ws
git submodule update --init --recursive" there is nothing happened.
![image](https://user-images.githubusercontent.com/35118859/50861593-2b44d000-1367-11e9-9055-aff250edf17e.png)

BTW Could I install the PX4 in the same workspace which I install my v-slam algorithm?

**Comment by zxp771** [comment]
Hi @szebedy 
I figure out the problem and tried to run the command in your introduction.
When I run the "roslaunch px4 mavros_posix_sitl.launch" it will show this error:
![image](https://user-images.githubusercontent.com/35118859/50862891-de62f880-136a-11e9-84bc-b0ae383fa843.png)
Will it impact other processing?


BTW 
1. I'm confused with the whycon you use, what's the purpose do you use that?
2. Could I install the PX4 in the same workspace which I install my v-slam algorithm?

**Comment by szebedy** [comment]
How did you figure out the problem? Do you have my [px4 fork](https://github.com/szebedy/px4) in the px4 folder?

1. As stated in my description, [my research paper](https://arxiv.org/abs/1809.08022) and if you googled it, whycon is a visual marker tracker for localizing a visual marker
2. You can do anything you please

**Comment by zxp771** [comment]
Hi@szebedy

1. I install the PX4 as https://github.com/UCM-M143/MavRos-takeoff-n-land said.
I think maybe I just run the command in the wrong folder.
2. Yes, I googled the whycon, but I think my problem is how to use it in the simulation environment.
3,Thanks for your reply.

Thanks for your help and share!It's really useful!

**Comment by zxp771** [comment]
Hi @szebedy 

I noted that you implemented the ewok for collision avoidance.
But I haven't seen any installation introduction for it.
Do you use the project in your code here?
Should I install the ewok by myself first then run your project for simulation?

**Comment by szebedy** [comment]
Hi @zxp771,

A modified version of the ewok source code can be found in the [trajectory planner](https://github.com/szebedy/autonomous-drone/blob/master/src/trajectory_planner/src/trajectory_planner.cpp) folder of my repository. I basically took the classes (includes) from ewok and modified one of their example source files to work with my application.

**Comment by zxp771** [comment]
Hi@szebedy 
Thanks for your reply.
I checked your code and the example you added in the folder.
Thanks for your sharing.

**Comment by zxp771** [comment]
Hi @szebedy 

I want to run the simulation environment on my computer
But I check your intel_aero launch file.
Do I need to install intel realsense package first then run the simulation test?

**Comment by szebedy** [comment]
Hi @zxp771 

If you want to [simulate, launch](https://github.com/szebedy/autonomous-drone#launch-file) the simulation launch file. It is still not going to work if you have the official PX4 repository and not my [PX4 fork](https://github.com/szebedy/px4), because I created a simulation environment dedicated for my autonomous drone repository.

Realsense package is only needed if you want to execute the code on the Intel Aero RTF drone. For that you can follow installation instructions [here](https://github.com/intel-aero/meta-intel-aero/wiki/05-Autonomous-drone-programming-with-ROS#installation).

**Comment by zxp771** [comment]
Hi @szebedy 
Thanks for your reply and sharing.
One more question: How do you build the Gazebo simulation environment?
I mean if I want to test the different simulation environment(not use your build but use my own one or change the target position on your simulation environment) which part should I modify by myself?

**Comment by szebedy** [comment]
Hi @zxp771,

You can change the models and worlds inside the `sitl_gazebo` submodule found in the folder `px4/Tools/sitl_gazebo`.

You can find [some example commits here](https://github.com/szebedy/sitl_gazebo/commits/0dfbfd536012843ce038bc40c358197b26c307cf) that show you how I did it.
