### ISSUE TITLE
Problems with downloading PX4 Gazebo simulator

### ISSUE THREAD

**Issue by dominiknatter** [szebedy/autonomous-drone#5]
Hi @szebedy ,

first of all thanks for sharing your code!
I have installed Ubuntu 16.04 and installed ROS according to your explanations. I can also both prepare the tools for building PX4 and download the source files from your account.
However, when trying to update the submodules, I get the following error (I have entered the command twice, so that is why here you cannot see all the submodules that worked):

![submodules_error](https://user-images.githubusercontent.com/46818571/51392856-811f3200-1b36-11e9-94a8-70b4aad384d7.png)

This leaves me behind with an empty folder “~/catkin_ws/px4/src/modules/uavcan/libuavcan”. It seems that I am not able to use the commit e1c9a4f5064a336295125da25c0542a5cd601dd7, but the most recent one (i.e. 67da0aae7dd4eedae7905ab98941592cebab4723) works fine if I simply clone it with “git clone https://github.com/UAVCAN/libuavcan” in ~/catkin_ws/px4/src/modules/uavcan. This is seen here:

![submodule_newer_success](https://user-images.githubusercontent.com/46818571/51392892-97c58900-1b36-11e9-8262-0d0bc17d6517.png)

However, the next line does not work then. This fatal error occurs:

![posix_sitl_error](https://user-images.githubusercontent.com/46818571/51392924-b62b8480-1b36-11e9-8a71-d7097a539a48.png)

I assume your code expects exactly the commit which is not working for me? Unfortunately, I have not found the answer in any other forum yet. Do you have any suggestions?

Thanks in advance!

**Comment by szebedy** [comment]
Hi @dominiknatter 

I'm not sure why this problem occurs, since the[ commit you mentioned ](https://github.com/UAVCAN/libuavcan/tree/e1c9a4f5064a336295125da25c0542a5cd601dd7)seems to be available.

I would delete my repository completely and start again from cloning it. Let me know if the problem still persists.

**Comment by dominiknatter** [comment]
Hi @szebedy 

I deleted my repository with rm -rf and was able to successfully clone your folder, just as before. But the update step again told me 'reference is not a tree' for the submodule in libuavcan.

**Comment by dominiknatter** [comment]
As a remark: I tried the two first answers of this topic (https://stackoverflow.com/questions/2155887/git-submodule-head-reference-is-not-a-tree-error), but neither helped. (Not sure if that topic 100% applies to my problem, though).

**Comment by dominiknatter** [comment]
Hi @szebedy 

I raised this issue in the repository of libuavcan directly. Apparently they have deleted some old branches a few days ago (see [here](https://github.com/UAVCAN/libuavcan/issues/194) for more information).

Do you think your code would work with a newer commit? If my try mentioned above was correctly executed, it would not work with the newest commit.

As I mentioned in the other forum/issue, I found a [repository](https://github.com/dagar/libuavcan/tree/master_upstream_nuttx_irq_changes) that looks quite similar. So I tried from the beginning (i.e. with cloning your repository). For the missing libuavcan I used the mentioned repository.

In that repository, I used `git submodule update --init --recursive` to get all referenced submodules (which then again are the newest of their type and therefore probably do not match the ones you used - that could be a problem. And checking out everything manually is not my first priority). Anyway, using `make posix_sitl_default gazebo` now seemed to work, but then in the end raised this big error:

![fail_using_repo_of_dagar_1](https://user-images.githubusercontent.com/46818571/51431703-dfc6d780-1c2c-11e9-990b-d4c118b0dfc1.png)
![fail_using_repo_of_dagar_2](https://user-images.githubusercontent.com/46818571/51431706-e48b8b80-1c2c-11e9-9b0f-2f7e961c6cee.png)

Does this help for finding any suggestions? For the time being, I've run out of ideas. Apparently this newest method did not get rid of the error. Concerning the part with mavlink: I cannot assure that this error has not been here around since the beginning, maybe it occured in the middle of the `make posix_sitl_default gazebo` output and I did not see it up to now.

Sorry for the inconveniences.

**Comment by szebedy** [comment]
Hi @dominiknatter thanks for figuring out the problem.

Can you try the following:
```
cd ~/catkin_ws
rm -rf px4
git clone https://github.com/PX4/Firmware.git px4 
cd px4
```

Then change line 23 the ~/catkin_ws/px4/.gitmodules file
from `url = https://github.com/px4/sitl_gazebo.git` 
to `url = https://github.com/szebedy/sitl_gazebo.git`

Also change line 16 of ~/catkin_ws/px4/launch/mavros_posix_sitl.launch file
from     `<arg name="sdf" default="$(find mavlink_sitl_gazebo)/models/$(arg vehicle)/$(arg vehicle).sdf"/>`
to    `<arg name="sdf" default="$(find mavlink_sitl_gazebo)/models/iris_r200/iris_r200.sdf"/>`

For reference see https://github.com/szebedy/px4/compare/fbf5ecd3ad160eea1a0ab3965513ceae54298a52...37ca96416b23e9a115b420301648d17a75d46613

Then finish the installation with

```
cd ~/catkin_ws/px4
git submodule update --init --recursive
make posix_sitl_default gazebo
cd ~/catkin_ws
catkin_make
source ./devel/setup.bash
```

**Comment by dominiknatter** [comment]
Hi @szebedy 
I executed the demanded changes, but upon calling `git submodule update --init --recursive` I get another checkout error with your repository:

![checkout_error_adapted_repo](https://user-images.githubusercontent.com/46818571/51437786-28b97300-1ca3-11e9-8c25-aad825d00ee0.png)

Edit: Using `git submodule sync` before `git submodule update` (as suggested [here](https://stackoverflow.com/questions/2155887/git-submodule-head-reference-is-not-a-tree-error)) made it possible to run everything without an error (as far as I can tell). Although no window showing a quadcopter popped up, that's a bit suspicious.

Anyway, I will try downloading the SVO 2.0 now and then try a launch. I'll keep you updated!

**Comment by szebedy** [comment]
@dominiknatter 

Sorry I forgot that my .gitmodules file will still point to my px4 fork. I edited my previous comment so that the `git submodule update --init --recursive` is only executed inside the px4 folder.

**Comment by dominiknatter** [comment]
@szebedy 

Ok to be totally sure I started over with deleting my px4 folder and followed your edited comment. Now I got this at the end of the execution of `git submodule update --init --recursive`. I do not know to what this SHA should belong though (or more like: from where it arised).

![checkout_error_sitl_gazebo](https://user-images.githubusercontent.com/46818571/51437991-771c4100-1ca6-11e9-9d21-1dae094d35e8.png)

**Comment by szebedy** [comment]
That is the newest commit of the original https://github.com/PX4/sitl_gazebo/commits/master

Looks like you didn't update the px4/.gitmodules file to use my sitl_gazebo fork.

Change line 23 px4/.gitmodules
from url = https://github.com/px4/sitl_gazebo.git
to url = https://github.com/szebedy/sitl_gazebo.git

**Comment by dominiknatter** [comment]
I am very sorry to tell you that I did that, see here:

![changed_line_23_gitmodules](https://user-images.githubusercontent.com/46818571/51438371-b305d500-1cab-11e9-82c7-2a5bc7d37f6e.png)

Shall I try using `git submodule sync` before `git submodule update` again?

**Comment by szebedy** [comment]
It's weird that it's still trying to reach the repository from px4...

How about this
```
cd ~/catkin_ws/px4/Tools
rm -rf sitl_gazebo
git clone https://github.com/szebedy/sitl_gazebo.git sitl_gazebo
cd ~/catkin_ws/px4
make posix_sitl_default gazebo
```

**Comment by dominiknatter** [comment]
I cloned it, `make posix_sitl_default gazebo` printed half a screen of (successful) commands and then this:

![error_new_sitl_gazebo_clone](https://user-images.githubusercontent.com/46818571/51438636-03cafd00-1caf-11e9-8918-8d1063203d4b.png)

haven't touched it yet. But if this is what you expected with your change, I assume to press y and enter next.

**Comment by szebedy** [comment]
@dominiknatter hit y and enter

**Comment by dominiknatter** [comment]
@szebedy 
it seemed to finish without an error and in the end printed `make[1]: Leaving directory '/home/dominik/catkin_ws/px4'`. So again, no window showing a quadcopter popped up. If you think that should be no problem, I will try to succeed with the installation, else I am happy to help you investigate further.

**Comment by szebedy** [comment]
@dominiknatter Could be alright. Please proceed with the installation guide and see what happens when you run the simulation with `roslaunch offboard_control simulation.launch`

**Comment by dominiknatter** [comment]
hi @szebedy 

I continued with the installation including the external instructions for SVO. SVO tests produced the expected results.

Following the chapter "Usage/Simulation" with only 2 terminals and a launch file brought this up:

![missing_intel_aero_launch_file](https://user-images.githubusercontent.com/46818571/51439710-6972b580-1cbe-11e9-970a-9d9dcc2d3ffc.png)

If this concerns the intel_aero.launch in `/catkin_ws/src/offboard_control/launch/`: I double-checked whether I ran `source ./devel/setup.bash` in `~\catkin_ws` and yes, I did run it.

So I tried the other startup method using 7 terminals and no launch file. The first terminal brought this up after calling `roslaunch px4 mavros_posix_sitl.launch`:

![startup_iris_error](https://user-images.githubusercontent.com/46818571/51439716-8c04ce80-1cbe-11e9-84c3-9af15d152d47.png)

I again double-checked whether I renamed line 16 of `~/catkin_ws/px4/launch/mavros_posix_sitl.launch` in the way you stated and yes, I did.

**Comment by szebedy** [comment]
@dominiknatter 

Thanks for noticing this. Forgot to mention in the installation guide that you need to copy the [calibration and launch files](https://github.com/szebedy/autonomous-drone/tree/master/vio_calibration/svo_aero) to the svo installation folder. If you show me the contents of `~\svo_ws` I can tell you where exactly.

**Comment by szebedy** [comment]
@dominiknatter 

Can you also try to change line 16 of ~/catkin_ws/px4/launch/**posix_sitl.launch** file (**not just mavros_posix_sitl.launch**)
from `<arg name="sdf" default="$(find mavlink_sitl_gazebo)/models/$(arg vehicle)/$(arg vehicle).sdf"/>`
to `<arg name="sdf" default="$(find mavlink_sitl_gazebo)/models/iris_r200/iris_r200.sdf"/>`

**Comment by dominiknatter** [comment]
@szebedy 

See the first 2 levels of `~\svo_ws` here:

![content_of_svo_ws](https://user-images.githubusercontent.com/46818571/51442573-89b26c80-1cde-11e9-9577-6c82f8c4a145.png)

I changed line 16 of said file, but the same errors when calling `roslaunch px4 mavros_posix_sitl.launch` within the first of 7 terminals occurred.

**Comment by szebedy** [comment]
@dominiknatter 

I checked this problem today with a fresh Ubuntu 16.04 install. I was able to launch the simulator just by replacing the libuavcan repository with the latest version. I commited this change so you could remove px4 folder pull the changes, and init submodules again, or just apply the same changes:
```
cd ~/catkin_ws/px4/modules/uavcan
rm -rf libuavcan
git clone https://github.com/UAVCAN/libuavcan.git libuavcan
```

Could you show me the contents of `~/svo_ws/build/svo_ros` and `~/svo_ws/src/rpg_svo_example`?

**Comment by dominiknatter** [comment]
Hi @szebedy 
thanks for trying. I am not 100% sure what you meant, so I'll try to recap:
 - I deleted my folder `~/catkin_ws/px4` (as I had no folder uavcan in it, because for the last try I used the commit of github.com/px4/firmware, not yours...)
 - in `~/catkin_ws` I used `git clone https://github.com/szebedy/px4.git`
 - in `~/catkin_ws` I used `git submodule update --init --recursive`
 - it was unable to checkout libuavcan (it said e1c9a4f5064a336295125da25c0542a5cd601dd7 is not a tree), so I went to `~/catkin_ws/px4/src/modules/uavcan`, deleted the empty folder `libuavcan` and used `git clone https://github.com/UAVCAN/libuavcan.git libuavcan`.

Was that all and correct? Or do I still have to change `~/catkin_ws/px4/launch/mavros_posix_sitl.launch` and `~/catkin_ws/px4/.gitmodules` (and `~/catkin_ws/px4/launch/posix_sitl.launch`) again?

Be happy to see the content of `~/svo_ws/build/svo_ros` and `~/svo_ws/src/rpg_svo_example` here:

![folder_content_svo_ros_rpg_svo_example](https://user-images.githubusercontent.com/46818571/51484727-95fcff00-1d9c-11e9-8e2b-af4f676e446b.png)

PS: I think in your last message you wanted to write `cd ~/catkin_ws/px4/src/modules/uavcan` instead of `cd ~/catkin_ws/px4/modules/uavcan` (missing the folder src)

**Comment by szebedy** [comment]
@dominiknatter 

I updated the autonomous-drone repository to fix the problems with libuavcan. You could have had the same results just by deleting ~/catkin_ws and cloning my repository again.

Technically what you did was correct but you still have the "old" version of my repository with fix applied by you. (For git this makes a difference, so it will be difficult to get more updates from me but for the moment you have the same source files)

With github.com/px4/firmware it's never going to work because they don't have the simulation environment set up for this specific repository. I created a simulation world with a simulated intel aero rtf  drone inside the sitl_gazebo submodule of px4.

I think the folder we were looking for is `~/svo_ws/src/rpg_svo_example/svo_ros`, can you please show the contents of it?

To make sure can you also show the output of `cat ~/svo_ws/devel/setup.bash`

**Comment by dominiknatter** [comment]
hi @szebedy 
oh I see. So to be sure I deleted ~/catkin_ws, cloned your repository again with `git clone https://github.com/szebedy/autonomous-drone.git catkin_ws` and updated the submodules with `cd ~/catkin_ws` and `git submodule update --init --recursive`. That worked indeed, but `cd ~/catkin_ws/px4` && `make posix_sitl_default gazebo` unfortunately yielded this [common](https://github.com/szebedy/autonomous-drone/issues/5#issuecomment-455810577) error:

![new_old_error_sitl_mavlink_1](https://user-images.githubusercontent.com/46818571/51487900-78339800-1da4-11e9-9fe3-248b71aa130a.png)
![new_old_error_sitl_mavlink_2](https://user-images.githubusercontent.com/46818571/51487910-7ec20f80-1da4-11e9-9749-92dce528a158.png)


See the demanded output here:
![output_of_svo_ros_and_setup_bash](https://user-images.githubusercontent.com/46818571/51487371-6998b100-1da3-11e9-8214-39d3eb5f5988.png)

**Comment by szebedy** [comment]
@dominiknatter You should be able to launch svo after copying the configuration files with
```
cp -r ~/catkin_ws/vio_calibration/svo_aero ~/svo_ws/src/rpg_svo_example/svo_ros/
```
Can you confirm that this works afterwards?
```
cd ~/svo_ws/
source ./devel/setup.bash
roslaunch svo_ros intel_aero.launch
```

I'm not sure why you get that error since I was able to build px4 today without any errors on a fresh Ubuntu 16.04 install just by following my installation instructions. It looks like my sitl_gazebo version is not compatible with your mavlink installation. Did you install ROS based on my instructions or did you already have it installed? Can you execute the following command and try again?
```
sudo /opt/ros/kinetic/lib/mavros/install_geographiclib_datasets.sh
```
Sometimes when you copy a block of commands and something occurs, not all of them are executed. Make sure to check that all installation steps were successful line by line.

**Comment by dominiknatter** [comment]
hi @szebedy 
I copied the configuration files. `roslaunch svo_ros intel_aero.launch` prints out some lines of [INFO] and [WARNING] and at some point stops throwing any commands at all. `rosnode list` lists /svo and `rostopic list` lists like a dozen /svo/... commands too - so I guess that works.

I did install (or tried to install) it based on your instructions. However, as your suggested command does not offer any changes (it returns something like "already up to date, skip"), I will make sure to uninstall everything concerning ROS and Gazebo and pursuing a new install line by line tomorrow.

**Comment by szebedy** [comment]
The only thing I can imagine is that when you cloned and built the original px4 firmware (with make posix_sitl_default gazebo), it installed a newer version of mavlink with it, which is not compatible with my repository anymore. If you don't manage to make it work I'd recommend an Ubuntu reinstall because it might be faster (I was done with the whole thing in an hour).

You could also try to make my code work with the newest px4 firmware, I basically only changed the px4/Tools/sitl_gazebo submodule (apart from that launch file) in order to have customized models and worlds that simulate my application.

For reference you can see all commits here that show you how I did it. https://github.com/szebedy/sitl_gazebo/commits/0dfbfd536012843ce038bc40c358197b26c307cf

I am closing this issue since thanks to your remarks it should work now if installed as per instructions.

Happy coding!

**Comment by logindiamant** [comment]
Hi! I solve problem by reinstall version of mavlink to ros-kinetic-mavlink_2018.9.17-1_amd64.deb
[https://github.com/szebedy/autonomous-drone/issues/5#issuecomment-455810577](url)
So, delete ros-kinetic-mavlink by Synaptic...
Install mavlink ros-kinetic-mavlink_2018.9.17-1_amd64.deb
sudo apt-get install ros-kinetic-mavros
sudo apt-get install ros-kinetic-mavros-extras

**Comment by dominiknatter** [comment]
@szebedy 
Although a first reinstall of Ubuntu did not bring any success, I wanted to thank you for your thorough support during the last days!

@logindiamant 
Sorry, I am not sure I understood everything. To recap:
 - You used the software 'Synaptic Package Manager' to delete the package ros-kinetic-mavlink.
 - Then you used the same software to install mavlink ros-kinetic-mavlink_2018.9.17-1_amd64.deb
 - you finished with `sudo apt-get install ros-kinetic-mavros` and `sudo apt-get install ros-kinetic-mavros-extras`.

Was that correct?
How far did you go in the installation guide before doing this? Did you execute everything up to `make posix_sitl_default gazebo`?

**Comment by szebedy** [comment]
Did you also install the 64 bit desktop version of ubuntu?

**Comment by dominiknatter** [comment]
Yes, see my configuration here:

![current_ubuntu_setup](https://user-images.githubusercontent.com/46818571/51603674-c1056100-1f0a-11e9-862b-55a77b75f3ed.png)

I work on a dual-boot system with Windows 10 running on another partition, but I hope that does not influence anything here.

**Comment by dominiknatter** [comment]
btw, concerning your general idea that a ROS reinstall alone is not enough: indeed during my last ROS reinstall, I saw that for each of these 3 commands

`sudo apt-get install ros-kinetic-desktop-full`
`sudo apt install ros-kinetic-mavros ros-kinetic-mavros-extras`
`sudo apt-get install libeigen3-dev ... ros-kinetic-sophus`

I got an output like "0 to upgrade, 638 to newly install, 0 to remove and 2 not to upgrade", so I thought those '2 not to upgrade' might be problematic / what you meant. After the complete Ubuntu reinstall I paid attention again and it stated '0 not to upgrade' for each of those commands. But apparently that fact did not help though.

**Comment by szebedy** [comment]
@logindiamant how did you install mavlink ros-kinetic-mavlink_2018.9.17-1_amd64.deb? Do you mean [this](https://github.com/mavlink/mavlink-gbp-release/releases/tag/debian%2Fros-kinetic-mavlink_2018.9.17-0_xenial)?
Can you share a link where to find this and how to install it?

**Comment by logindiamant** [comment]
https://drive.google.com/file/d/1Su5Ykg08xJZcytiywttlJ4EPBCvU1tYd
Just double click file, opened gui, click install...

**Comment by mkpvishnu** [comment]
I am getting the same error.
Could anyone just recap what i should do now?

**Comment by szebedy** [comment]
I updated the repository with the install file required for mavlink. First pull the updates:
```
cd ~/catkin_ws
git checkout master
git fetch --all
git reset --hard origin/master
```
Then reinstall mavros:
```
sudo apt-get remove ros-kinetic-mavlink
sudo apt install ./ros-kinetic-mavlink_2018.9.17-1_amd64.deb
sudo apt install ros-kinetic-mavros ros-kinetic-mavros-extras
```

**Comment by 150202029** [comment]
hi 
![Ekran Görüntüsü - 2020-02-03 23-22-31](https://user-images.githubusercontent.com/48123475/73688064-486bdf80-46dc-11ea-9f66-2e811d69c366.png)
@szebedy
