### ISSUE TITLE
SVO scale position

### ISSUE THREAD

**Issue by logindiamant** [szebedy/autonomous-drone#6]
Hi @szebedy!

Can you have a problem with scale in odometry?
I try to use stereo cam RealSense with high accuracy IMU in SVO 2.0 odometry...
When I cyclically shift a drone between two stationary points A(x1,y1,z1) and B(x2,y1,z1), drone in any iterations flies in new points with low, and low, and low scale

May be you know some parameters in config files to solve this problem?

Some of parameter in my yaml file

pipeline_is_stereo: True
automatic_reinitialization: True # When lost, stereo can recover immediately
grid_size: 35
use_async_reprojectors: True
use_imu: True
poseoptim_prior_lambda:       2.0
img_align_prior_lambda_rot:   5.0
img_align_prior_lambda_trans: 0.0

use_threaded_depthfilter: True
quality_min_fts: 40
quality_max_drop_fts: 80

max_depth_inv: 0.1
min_depth_inv: 10.0
mean_depth_inv: 0.5

map_scale: 1.0
kfselect_criterion: DOWNLOOKING
kfselect_numkfs_upper_thresh: 180
kfselect_numkfs_lower_thresh: 90
kfselect_min_dist_metric: 0.001
kfselect_min_angle: 6
kfselect_min_disparity: 40
kfselect_min_num_frames_between_kfs: 0

img_align_est_illumination_gain: true
img_align_est_illumination_offset: true
depth_filter_affine_est_offset: true
depth_filter_affine_est_gain: true
reprojector_affine_est_offset: true
reprojector_affine_est_gain: true

**Comment by szebedy** [comment]
map_scale: 1.0 parameter means that when you start SVO, the average distance from the camera to the ground needs to be 1 meter. This needs to be done very precisely otherwise the output of SVO will be imprecise and vision based navigation will not work properly.

During real flight tests I measured this 1 meter from the ground and always launched SVO while holding the drone in my hand 1 meter above the ground. If I held the drone a little bit higher or lower (error >= 10 cm) then I noticed huge oscillations during the flight.

**Comment by logindiamant** [comment]
Is map_scale as parameter work in stereo odometry?

I need automatic_reinitialization in every failure
As I know, scale is calculate from 2 cam in every reinitialization...

**Comment by szebedy** [comment]
I don't have any experience with stereo odometry, better ask from the developers of SVO.

**Comment by logindiamant** [comment]
Problem is
![screenshot from 2019-01-25 18-13-09](https://user-images.githubusercontent.com/39023197/51751867-878a4c80-20e8-11e9-9a60-2ba80ef3b0f9.png)

**Comment by logindiamant** [comment]
I solve it!

![image](https://user-images.githubusercontent.com/39023197/52074946-9f1c7600-25bd-11e9-921d-06c1c892d643.png)
![snapshot39](https://user-images.githubusercontent.com/39023197/52074965-ae9bbf00-25bd-11e9-92a7-28913ce503e5.png)
![snapshot40](https://user-images.githubusercontent.com/39023197/52074972-b22f4600-25bd-11e9-83f0-4a929397a8a0.png)
![snapshot41](https://user-images.githubusercontent.com/39023197/52074982-b8252700-25bd-11e9-9276-5045472b7911.png)
![snapshot42](https://user-images.githubusercontent.com/39023197/52074984-ba878100-25bd-11e9-948c-35d9bbc458d2.png)
![snapshot44](https://user-images.githubusercontent.com/39023197/52074992-bf4c3500-25bd-11e9-9c84-3c25fb667e7c.png)
![snapshot45](https://user-images.githubusercontent.com/39023197/52074998-c2472580-25bd-11e9-8be6-025ff76d95aa.png)

yaml file

pipeline_is_stereo: true
automatic_reinitialization: true

#grid_size: 35
use_async_reprojectors: true #false
use_imu: true
poseoptim_prior_lambda: 1.0 #0.0

#poseoptim_using_unit_sphere: true

img_align_prior_lambda_rot: 50.0 #0.0
img_align_prior_lambda_trans: 0.01 #0.0

img_align_max_level: 2 #4
img_align_min_level: 1 #2

img_align_robustification: true #false
#img_align_use_distortion_jacobian: true #false
img_align_est_illumination_gain: true #false
img_align_est_illumination_offset: true #false

#poseoptim_thresh: 2.0

seed_convergence_sigma2_thresh: 20 #200

use_threaded_depthfilter: true #true

quality_min_fts: 40 #50
quality_max_drop_fts: 80 #40

max_depth_inv: 0.1 #1.0/50.0
min_depth_inv: 10.0 #1.0/0.5
mean_depth_inv: 0.5 #1.0/2.0

map_scale: 1 #5.0

kfselect_criterion: DOWNLOOKING #FORWARD
kfselect_numkfs_upper_thresh: 180 #120
kfselect_numkfs_lower_thresh: 90 #70
kfselect_min_dist_metric: 0.001 #0.01
kfselect_min_angle: 6 #20
kfselect_min_disparity: 40 #40
kfselect_min_num_frames_between_kfs: 0 #2

depth_filter_affine_est_offset: true #true
depth_filter_affine_est_gain: true #false

reprojector_affine_est_offset: true #true
reprojector_affine_est_gain: true #false

**Comment by bednarhonza** [comment]
Hi @logindiamant,
I am using also RealSense, specifically D435i and I'm facing the same issue as you. I have tried your settings, but it did not help, still the same. Did you find the values just experimentally?

Thanks,
Jan

**Comment by logindiamant** [comment]
Hi, @Jwenda,
I find this values just experimentally
We abandoned the visual odometry, now use 3D lidars for localization
Need high quality hard time synchronization CAMs&IMU
High quality calibration CAMs&IMU procedure to find rotation matrises
Need some fusion software (Kalman filtering) to use IMU information
Finally, may be you find the same set of parameters...

**Comment by bednarhonza** [comment]
Hi @logindiamant,
alright, thanks. I had a mistake in the camera calibration, now it works much better, but I have to test it furthermore.
