### ISSUE TITLE
Failed to load plugin libgazebo_ros_camera

### ISSUE THREAD

**Issue by mkpvishnu** [szebedy/autonomous-drone#7]
[Msg] Waiting for master.
[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 10.0.2.15
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 10.0.2.15
[Wrn] [msgs.cc:1655] Conversion of sensor type[depth] not suppported.
[Err] [Plugin.hh:165] Failed to load plugin libgazebo_ros_camera.so: libCameraPlugin.so: cannot open shared object file: No such file or directory
[Err] [Plugin.hh:165] Failed to load plugin libgazebo_ros_openni_kinect.so: libDepthCameraPlugin.so: cannot open shared object file: No such file or directory
[Err] [Distortion.cc:63] Pincushion model is currently not supported. Please use a negative k1 coefficient for barrel distortion
[Err] [Distortion.cc:80] Currently only Barrel Distortion is supported. Distortion will not be applied.
[Err] [Plugin.hh:165] Failed to load plugin libgazebo_ros_camera.so: libCameraPlugin.so: cannot open shared object file: No such file or directory
[Dbg] [gazebo_mavlink_interface.cpp:133] <joint_name> not found for channel[0] no joint control will be performed for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:133] <joint_name> not found for channel[1] no joint control will be performed for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:133] <joint_name> not found for channel[2] no joint control will be performed for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:133] <joint_name> not found for channel[3] no joint control will be performed for this channel.
[Wrn] [gazebo_mavlink_interface.cpp:122] joint [zephyr_delta_wing::propeller_joint] not found for channel[4] no joint control for this channel.
[Wrn] [gazebo_mavlink_interface.cpp:122] joint [zephyr_delta_wing::flap_left_joint] not found for channel[5] no joint control for this channel.
[Wrn] [gazebo_mavlink_interface.cpp:122] joint [zephyr_delta_wing::flap_right_joint] not found for channel[6] no joint control for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:133] <joint_name> not found for channel[7] no joint control will be performed for this channel.
[Wrn] [msgs.cc:1655] Conversion of sensor type[depth] not suppported.
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris_r200/motor_speed/0, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris_r200/motor_speed/1, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris_r200/motor_speed/2, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris_r200/motor_speed/3, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris_r200/imu, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris_r200/motors, deleting message. This warning is printed only once.
INFO  [simulator] Got initial simulation data, running sim..
INFO  [pwm_out_sim] MODE_16PWM
INFO  [mavlink] mode: Normal, data rate: 4000000 B/s on udp port 14556 remote port 14550
INFO  [mavlink] mode: Onboard, data rate: 4000000 B/s on udp port 14557 remote port 14540
INFO  [mavlink] MAVLink only on localhost (set param MAV_BROADCAST = 1 to enable network)
pxh> INFO  [logger] logger started (mode=all)
INFO  [logger] Start file log
INFO  [logger] Opened log file: rootfs/fs/microsd/log/2019-01-30/07_35_16.ulg
INFO  [Unknown] EKF aligned, (pressure height, IMU buf: 22, OBS buf: 14)
gzserver: /build/ogre-1.9-mqY1wq/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreRenderSystem.cpp:546: virtual void Ogre::RenderSystem::setDepthBufferFor(Ogre::RenderTarget*): Assertion `bAttached && "A new DepthBuffer for a RenderTarget was created, but after creation" "it says it's incompatible with that RT"' failed.

**Comment by caomxin** [comment]
same problem!

**Comment by szebedy** [comment]
@mkpvishnu @caomxin 

Please let me know if you managed to solve the problem. You are also very welcome to do a pull request

**Comment by szebedy** [comment]
@mkpvishnu @caomxin did you manage to solve this problem?

**Comment by mkpvishnu** [comment]
I still don't know where the exact problem is, but I managed reinstall the entire thing including the OS with the exact versions of plugins as mentioned. It worked like charm.

**Comment by szebedy** [comment]
@mkpvishnu Okay, cool, assuming this problem results from an error in the installation process

**Comment by ldg810** [comment]
@mkpvishnu @szebedy I had same problem "Failed to load plugin libgazebo_ros_camera.so: libCameraPlugin.so: cannot open shared object file: No such file or directory" yesterday.
Even though I set GAZEBO_PLUGIN_PATH correctly, the problem was not solved.
I am using docker environment and I re-build many times and found a thing. When I install many ros pakcages(such as ros-dashing-ros-pkgs) at the same time in the process of set up environment, the problem is not occured.

I don't know exactly what cause the problem but I agree with "this problem results from an error in the installation process".
