### ISSUE TITLE
unable to update the PX4 version on the intel aero ready to fly drone

### ISSUE THREAD

**Issue by aomezzine** [szebedy/autonomous-drone#8]
Hi szebedy,
Thank you for sharing your code, very interesting.
In order to use visual odometry (SVO), we have to update the PX4 version on the intel aero ready to fly drone.
Unfortunately, I was unable to compile the px4 version v1.8.2 on intel RTF done (by following that two links (1) https://docs.px4.io/en/complete_vehicles/intel_aero.html and (2) https://dev.px4.io/en/setup/building_px4.html)

Can you tell me how did you manage to do that?

Thank you very much for your help

**Comment by szebedy** [comment]
Hi @aomezzine 

I used the flashing script from intel. See: https://github.com/intel-aero/meta-intel-aero/wiki/02-Initial-setup#flashing-the-flight-controller-rtf-only
I think you can stick to the recommended version, but v1.8.2 should work as well.

**Comment by aomezzine** [comment]
Hi @szebedy 
Thank you for the reply. 
The intel script install the version 1.6.5.  Did you use the px4 version 1.6.5 ? Is it able to support visual odometry SVO ?
Because when I try your code on the intel aero with v1.6.5 as PX4 version (and after tuning parameters in qgroundcontrol to enable vision position), the topic “/mavros/local_position/pose” became empty and did not show any values.

**Comment by szebedy** [comment]
Yeah I had that problem too. You need SVO running to have the position estimates. But the drone needs to be in the air 1.5 meters above the ground (or whatever you set in ~/svo_ws/src/rpg_svo_example/svo_ros/intel_aero_imu.yaml -> map_scale) in order to initialize SVO. How do you break this vicious circle? Well what I did is I held the drone in front of my chest with one hand, while starting SVO through SSH on my laptop with the other hand. You need to measure the 1.5 meters, since if you're not holding it precisely it will oscillate during the flight (due to the scaling error). Once SVO was running I started all other nodes including offboard control with the launch file. As soon as the propellers start rotating you can slowly let go of the drone. Have fun!

**Comment by aomezzine** [comment]
Thank you @szebedy.
OK, I thought it was a version problem. 
In my case, I want first to test SVO and its precision for an indoor localization. Therefore, what I do is to hold the drone in my hand and try to move it without arming the motors (without propellers) and I examine the /svo/pose_imu (or /mavros/vision_pose/pose). Concerning the localization, I got a satisfactory result BUT the problem is that position is not shown in the mavros/local_position/pose.
So, do you think I have to arm the motors and activate the offboard mode in order to get information on that topic (mavros/local_position/pose)?

**Comment by szebedy** [comment]
I'm assuming you set [EKF2_AID_MASK](https://dev.px4.io/en/advanced/parameter_reference.html#EKF2_AID_MASK) to 24 (vision position fusion + vision yaw fusion). If I remember correctly as soon as you start sending the vision position estimates to px4 through mavros (topic /mavros/vision_pose/pose), the local position (topic /mavros/local_position/pose) will appear. My ROS node called "offboard control" does this here: https://github.com/szebedy/autonomous-drone/blob/8e371dd0af5947867c8b6280341f99b3a43ab12b/src/offboard_control/drone_control.cpp#L237
I don't think you need to or can arm the motors before the local position appears.

**Comment by aomezzine** [comment]
Yes I set the EKF2_AID_MASK to 24 via qgroundControl v3.4.4
Also, I verify that I got information through /mavros/vision_pose/pose. BUT, no information in  /mavros/local_position/pose.
When I modify the EKF2_AID_MASK to the default value, the /mavros/local_position/pose shows information.

**Comment by szebedy** [comment]
That's weird, maybe EKF doesn't like the estimates (rejects them because of inconsistency), but it's probably something else... Let me know if you figured it out.

**Comment by aomezzine** [comment]
Hi,
The ekf2_hgt_mode should be set to Barometric pressure in order to see information in mavros/local_position/pose (I set it to vision at the beginning). Did you set it to barometric pressure too ?

But I still have a big problem, the information in the topic (/mavros/local_position/pose) does not match with the topic (/mavros/vision_pose/pose). (I think that vision pose is not taken into consideration)

Are there additional parameters that must be changed ?

**Comment by szebedy** [comment]
what is your map_scale (in ~/svo_ws/src/rpg_svo_example/svo_ros/intel_aero_imu.yaml)? Do you initialize SVO with the drone at that height?

**Comment by aomezzine** [comment]
map_scale=1.0
I tried to initialize the svo with drone at 1m from the ground. In fact, I notice that /mavros/vision_pose/pose match the mouvement of the drone. But /mavros/local_position/pose still in 0, 0 in x and y even if I move the drone.

**Comment by szebedy** [comment]
I set EKF2_HGT_MODE​ to 3 and EKF2_ASP_DELAY​ to 200. Also I did not use IMU data, only vision. You might have to search for a solution in the PX4 issues.

**Comment by aomezzine** [comment]
Thank you for your help. The topic /mavros/local_position/pose still empty when I set ekf2_hgt_mode to 3. May be I should change other parameters for EKF2.

**Comment by aomezzine** [comment]
I solve the problem of the empty topic (/mavros/local_position_pose) by updating the px4 firmware v1.8.2.
Thank you @szebedy for your help.
