### ISSUE TITLE
SVO 2.0 binaries are not available from the website of robotics& perception group

### ISSUE THREAD

**Issue by sbyebss** [szebedy/autonomous-drone#9]
HI Szebedy:
Thank you for your sharing, but when I want to download the SVO 2.0 package from http://rpg.ifi.uzh.ch/svo2download.html, it is empty, do you know why this is? And do you know where I could download SVO 2.0 package now?

**Comment by sbyebss** [comment]
Oh! From here, right? I am sorry that I didn't give full notice to its GitHub introduction.
https://github.com/uzh-rpg/rpg_svo/wiki/Installation:-ROS

**Comment by sbyebss** [comment]
HI Szebedy:
 Could you please be kind to provide the SVO 2.0 binaries files?

**Comment by szebedy** [comment]
1. Go on the following link: http://rpg.ifi.uzh.ch/svo2download.html
2. Accept everything
3. "To download SVO 2.0 (Ubuntu 14.04 64 bit binaries and example code), in addition to agreeing to all terms of the license agreement, you must provide your real full name, institution, and valid e-mail address. Upon submission, an e-mail containing the download link will be sent to the address provided."

**Comment by sbyebss** [comment]
@szebedy I am very sorry that because of my low net speed. The inquiry form didn't come out. So I think it's empty. Now it's solved! Thank you very much!
